#!/usr/bin/env ruby
#
# This script connects to IB API and subscribes to L2 (depth of market) data for
# specific symbols

require 'bundler/setup'
require 'ib/symbols'
require_relative 'config'
require 'ruby_jard'
# Definition of what we want L2 data for.
# Realtime data subscriptions are required
symbols = [ IB::Symbols::Stocks.wfc,
            IB::Symbols::Futures.mini_dax,
            IB::Symbols::Forex[:gbpusd]
          ]

request_ids = {}
# First, connect to IB TWS.
ib = IB::Connection.new **Init.params  do | gw|

	# Subscribe to TWS alerts/errors
	gw.subscribe(:Alert) { |msg| puts msg.to_human }

	# Subscribe to MarketDepth events.
	gw.subscribe(:MarketDepth) do |msg|
		puts request_ids[msg.request_id].description + ": " + msg.to_human
	end

	# Set log level
	gw.logger.level = Logger::FATAL # DEBUG #FATAL

end
# Now we actually request L2 market data for the symbols we're interested in.
 symbols.each do | contract |
#  jard
  ids = ib.send_message :RequestMarketDepth,
                 :contract => contract,
                 :num_rows => 5
  request_ids[ids] = contract
end

puts "\nSubscribed to market data"
puts "\n******** Press <Enter> to cancel... *********\n\n"
STDIN.gets
puts "Cancelling market data subscription.."

market.each_pair { |id, contract| ib.send_message :CancelMarketDepth, :id => id }
