#!/usr/bin/env ruby
#
# This script connects to IB API and subscribes to  Account Summary Updates for certain tags

require 'bundler/setup'
require 'ib-api'
require_relative 'config'

# Definition of what we want listed
# possible tags
#            NetLiquidation,
#            TotalCashValue - Total cash including futures pnl
#            SettledCash - For cash accounts, this is the same as
#            TotalCashValue
#            AccruedCash - Net accrued interest
#            BuyingPower - The maximum amount of marginable US stocks the
#                account can buy
#            EquityWithLoanValue - Cash + stocks + bonds + mutual funds
#            PreviousDayEquityWithLoanValue,
#            GrossPositionValue - The sum of the absolute value of all stock
#                and equity option positions
#            RegTEquity,
#            RegTMargin,
#            SMA - Special Memorandum Account
#            InitMarginReq,
#            MaintMarginReq,
#            AvailableFunds,
#            ExcessLiquidity,
#            Cushion - Excess liquidity as a percentage of net liquidation value
#            FullInitMarginReq,
#            FullMaintMarginReq,
#            FullAvailableFunds,
#            FullExcessLiquidity,
#            LookAheadNextChange - Time when look-ahead values take effect
#            LookAheadInitMarginReq,
#            LookAheadMaintMarginReq,
#            LookAheadAvailableFunds,
#            LookAheadExcessLiquidity,
#            HighestSeverity - A measure of how close the account is to liquidation
#            DayTradesRemaining - The Number of Open/Close trades a user
#                could put on before Pattern Day Trading is detected. A value of "-1"
#                means that the user can put on unlimited day trades.
#            Leverage - GrossPositionValue / NetLiquidation
#            $LEDGER - Single flag to relay all cash balance tags*, only in base
#                currency.
#            $LEDGER:CURRENCY - Single flag to relay all cash balance tags*, only in
#                the specified currency.
#            $LEDGER:ALL - Single flag to relay all cash balance tags* in all
#
tags =  %w( NetLiquidation NetLiquidation InitMarginReq DayTradesRemaining )
# connect to IB TWS.

q =  Queue.new
ib = IB::Connection.new **Init.params do | gw |  
  ## Subscribe to foreseeable events before the connection is completed
  ## Subscribe to TWS alerts/errors
  gw.subscribe(:Alert){ |msg| puts msg.to_human }
  # Add message to the queue
  gw.subscribe(:AccountSummary){ |msg| q <<  msg }
  # After receiving results, wait for Confirmation from TWS. Then close queue
  gw.subscribe(:AccountSummaryEnd){  q.close }
  gw.logger.level = Logger::FATAL # DEBUG #:-- INFO -- WARN -- ERROR  -- FATAL
end

# request the  AccountSummary
request_id = ib.send_message :RequestAccountSummary, tags: tags.join(',')
# wait  for the data to return and print
while  p = q.pop
  puts p.to_human
end
#  closing the queue breaks while loop
puts "\n *** canceling Request ..."
ib.send_message :CancelAccountSummary, id: request_id
puts "done."	
sleep 0.5 


