#!/usr/bin/env ruby
#
# This script connects to IB API and subscribes to  Position Values which are updated regularly

# TWS-data are collected in a Queue and processed after the TWS signaled :PositionDataEnd. 

require 'bundler/setup'
require 'ib-api'

require_relative 'config'

q =  Queue.new
ib = IB::Connection.new **Init.params do | gw |  
#
## Subcribe to forseable events before the connection is completed
## Subscribe to TWS alerts/errors
  gw.subscribe(:Alert ){ |msg| puts msg.to_human }
  gw.subscribe(:PositionData){ |msg|  q << msg  }
  gw.subscribe(:PositionDataEnd) do |msg|
    puts "received PositionDataEmd:"
    puts  '*'* 50
    while p =  q.pop   # do until queue is empty?
      puts p.to_human
    end
		ib.send_message :CancelPositions
    sleep 0.5
  end

	gw.logger.level = Logger::FATAL # DEBUG  -- INFO -- WARN -- ERROR  -- FATAL
end
# request the  AccountSummary
  ib.send_message :RequestPositions

# the  output of queue ist processed asynchron
# No Need to use a Thread at this time
  sleep 0.5 



