#!/usr/bin/env ruby

# This script reproduces https://github.com/ib-ruby/ib-ruby/issues/12

require 'bundler/setup'
require 'ib-api'
require 'yaml'


# read items from console.yml
read_yml = -> (key) do
		YAML::load_file( File.expand_path('../config.yml',__FILE__))[key]
end

client  =  read_yml[ :client_id ]
port    =  read_yml[ read_yml[ :product ] ]


contract = IB::Stock.new :symbol=> 'AAPL'

# First, connect to IB Gateway.
ib = IB::Connection.new client_id: client , port: port 
ib.logger.level=Logger::INFO
ib.subscribe(:Alert) { |msg| puts msg.to_human }
ib.subscribe(:MarketDataType) { |msg| puts msg.to_human }
ib.subscribe(:TickGeneric, :TickString, :TickPrice, :TickSize) { |msg| puts msg.to_human }
ib.send_message :RequestMarketDataType, :market_data_type => :delayed
ib.send_message :RequestMarketData, id: 123, contract:  contract

puts "\nSubscribed to market data"
puts "\n******** Press <Enter> to cancel... *********\n\n"
gets
puts "Cancelling market data subscription.."

ib.send_message :CancelMarketData, id: 123
sleep 1
puts "Done."
